config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path("reports/", include("reports.urls")),
    path('admin/', admin.site.urls),
]

reports/urls.py
from django.urls import path

from . import views

app_name = "reports"
urlpatterns = [
	path("", views.index, name="index"),
	path("create", views.create, name="create"),
]

reports/models.py
import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Report(models.Model):
	class AchievementScoreChoices(models.TextChoices):
		VERY_GOOD	= "◎", _("◎")
		GOOD		= "◯", _("◯")
		SOSO		= "△", _("△")
		NG			= "✗", _( "✗")

	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	on_date = models.DateField()
	daily_title = models.TextField(blank=True)
	daily_comment = models.TextField(blank=True)
	weekly_target = models.TextField(blank=True)
	achievement_score = models.CharField(
		choices=AchievementScoreChoices,
		blank=True)
	achievement_comment = models.TextField(blank=True)
	goods = models.TextField()
	mores = models.TextField()
	nexts = models.TextField()
	

reports/forms.py
from django import forms
from .models import Report
from datetime import date

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = [
            'on_date',
			'daily_title',
            'daily_comment',
            'weekly_target',
            'achievement_score',
            'achievement_comment',
			'goods',
			'mores',
			'nexts'
        ]  # フォームに出したいフィールドを書く
        widgets = {
            'on_date': forms.DateInput(attrs={'type': 'date', 'class': 'input block w-full text-lg'}),
            'daily_title': forms.TextInput(attrs={'class': 'input input-ghost text-lg', 'placeholder': '今日の一言'}),
			'daily_comment': forms.Textarea(attrs={'rows': 3, 'class': 'textarea textarea_bordered h-24 w-full', 'placeholder': '今日の一言を記入'}),
            'weekly_target': forms.Textarea(attrs={'rows': 3, 'class': 'textarea textarea_bordered h-24 w-full'}),
            'achievement_score': forms.Select(choices=Report.AchievementScoreChoices, attrs={'rows': 3, 'class': 'select select-ghost'}),
            'achievement_comment': forms.Textarea(attrs={'rows': 3, 'class': 'textarea textarea_bordered h-24 w-full'}),
            'goods': forms.Textarea(attrs={'rows': 3, 'class': 'textarea textarea_bordered h-24 w-full'}),
            'mores': forms.Textarea(attrs={'rows': 3, 'class': 'textarea textarea_bordered h-24 w-full'}),
            'nexts': forms.Textarea(attrs={'rows': 3, 'class': 'textarea textarea_bordered h-24 w-full'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 初期値に今日の日付を設定する
        today = date.today()
        if not self.initial.get('report_date'):
               self.initial['on_date'] = today
        
        last_report = Report.objects.latest('on_date')
        if last_report.on_date.isocalendar()[:2] == today.isocalendar()[:2]:
              self.initial['weekly_target'] = last_report.weekly_target

reports/views.py
from collections import defaultdict
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Report
from .forms import ReportForm

def index(request):
	report_list = Report.objects.all().order_by('-on_date')
	weekly_groups = defaultdict(list)
	for item in report_list:
		week = item.on_date.isocalendar()[:2]
		weekly_groups[week].append(item)
	report_list_by_week = list(weekly_groups.values())
	form = ReportForm()
	context = {"report_list_by_week": report_list_by_week, 'form': form}
	return render(request, "reports/index.html", context)

def create(request):
	if request.method == 'POST':
		form = ReportForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse("reports:index"))
		else:
			form = ReportForm()
	return render(request, reverse('reports:index'), {'form': form})
	
def detail(request):
	return "detail"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html data-theme="retro">
	<head>
		<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
		{% comment %} <link href="{% static 'css/output.css' %}" rel="stylesheet" /> {% endcomment %}
		<link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
		<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
		<link href="https://cdn.jsdelivr.net/npm/daisyui@5/themes.css" rel="stylesheet" type="text/css" />
		<link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
	</head>
	<body class="w-full">
		<div class="navbar bg-white shadow-sm h-14 p-2 fixed z-40">
			<img src="{% static 'images/nippo_logo_transparent.png' %}" class="h-full"/>
		</div>
		<div class="pt-18">
			{% block mainblock %}
			{% endblock %}
		</div>
	</body>
</html>

templates/reports/_components/report_card.html
{% load markdownify %}
<div class="card w-full bg-base-200 card-sm shadow-sm">
	<div class="card-body">
		<div class="flex flex-row justify-between">
			<h2 class="card-title text-xl">{{report.on_date|date:"m/d l"}}</h2>
			<div class="tooltip tooltip-accent" id="copied-tooltip-{{report.id}}" data-tip="Click to copy report in MD.">
				<i id="copy-report-md-{{report.id}}" class="fa-regular fa-clipboard text-xl text-accent hover:cursor-pointer"></i>
			</div>
			{% include "reports/_components/report_md.html" with report=report%}
		</div>
		{% if report.daily_title or report.daily_comment %}
			<div class="w-full">
				<h3 class="text-lg font-bold">{{report.daily_title}}</h3>
				{{report.daily_comment | markdownify}}
			</div>
			<div class="divider my-2"></div>
		{% endif%}
		<div class="flex flex-col lg:flex-row align-middle lg:justify-between">
			<div class="w-full lg:w-2/5">
				<h3 class="text-lg font-bold">今週の目指す状態</h3>
				{{report.weekly_target | markdownify}}
			</div>
			<div>
				<div class="hidden lg:block lg:w-1/5">
					<i class="fa-solid fa-arrow-right"></i>
				</div>
				<div class="w-full m-2 lg:hidden">
					<i class="fa-solid fa-arrow-down"></i>
				</div>
			</div>
			<div class="w-full lg:w-2/5">
				<h3 class="text-lg font-bold">本日の達成度 {{report.achievement_score}}</h3>
				{{report.achievement_comment | markdownify}}
			</div>
		</div>
		<div class="divider my-2"></div>
		<div class="stats stats-vertical lg:stats-horizontal w-full">
			<div class="stat p-2">
				<div class="stat-title text-lg">
					<span class="status status-success"></span>
					<span class="font-bold text-base-content">GOOD</span>
				</div>
				<div class="stat-desc self-start text-base-content text-wrap">{{report.goods | markdownify}}</div>
			</div>
			<div class="stat p-2">
				<div class="stat-title text-lg">
					<span class="status status-warning"></span>
					<span class="font-bold text-base-content">MORE</span>
				</div>
				<div class="stat-desc self-start text-base-content text-wrap">{{report.mores | markdownify}}</div>
			</div>
			<div class="stat p-2">
				<div class="stat-title text-lg">
					<span class="status status-info"></span>
					<span class="font-bold text-base-content">NEXT</span>
				</div>
				<div class="stat-desc self-start text-base-content text-wrap">{{report.nexts | markdownify}}</div>
			</div>
		</div>
	</div>
</div>

templates/reports/_components/report_form.html
<div class="drawer-side bg-base-300 text-base-content h-full w-full md:w-1/2 p-4 z-50">
	<label for="report-form" aria-label="close sidebar" class="drawer-overlay"></label>
	<form action="{% url 'reports:create' %}" method="post" class="bg-inherit h-full w-full">
		{% csrf_token %}
		<div class='space-y-4'>
			<div class="flex justify-between align-middle">
				<legend><h1 class="text-2xl font-extrabold">今日を振り返ろう</h1></legend>
				<label for="report-form" class=""><i class="fa-solid fa-circle-xmark text-2xl"></i></label>
			</div>
			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
			<fieldset class="fieldset">
				<legend class="fieldset-legend text-lg">日付</legend>
				{{form.on_date}}	
			</fieldset>
			<fieldset class="fieldset">
				<legend class="fieldset-legend text-lg">今週の目指す状態</legend>
				{{form.weekly_target}}
			</fieldset>
			<fieldset class="fieldset">
				<legend class="fieldset-legend text-lg">本日の達成度</legend>
				{{form.achievement_score}}
			</fieldset>
			<fieldset class="fieldset">
				{{form.achievement_comment}}
			</fieldset>
			<fieldset class="fieldset">
				<legend class="fieldset-legend text-lg">GOOD</legend>
				{{form.goods}}
			</fieldset>
			<fieldset class="fieldset">
				<legend class="fieldset-legend text-lg">MORE</legend>
				{{form.mores}}
			</fieldset>
			<fieldset class="fieldset">
				<legend class="fieldset-legend text-lg">NEXT</legend>
				{{form.nexts}}
			</fieldset>
			<fieldset class="fieldset">
				{{form.daily_title}}
			</fieldset>
			<fieldset class="fieldset">
				{{form.daily_comment}}
			</fieldset>
			<input type="submit" class="btn btn-primary" value="作成">
		</div>
	</form>
</div>

templates/reports/_components/report_md.html
<textarea class="hidden" id="report-md-{{report.id}}">
{% if report.daily_title or report.daily_comment %}
##【{{report.daily_title}}】

{{report.daily_comment}}
{% endif %}

##【今週の目指す状態】

{{report.weekly_target}}


##【本日の達成度：{{report.achievement_score}}】

{{report.achievement_comment}}


##【GOOD】

{{report.goods}}


##【MORE】

{{report.mores}}


##【NEXT】

{{report.nexts}}

</textarea>
<script>
	$(`#copy-report-md-{{report.id}}`).on('click',function() {
		mdText = $(`#report-md-{{report.id}}`).text();
		console.log('copied Markdown report for {{report.id}}.');
		navigator.clipboard.writeText(mdText)
			.then(function() {
				$('#copied-tooltip-{{report.id}}').attr('data-tip', 'Copied!');
				$('#copied-tooltip-{{report.id}}').removeClass('tooltip-accent').addClass('tooltip-success');
			})
			.catch(function() {
				$('#copied-tooltip-{{report.id}}').attr('data-tip', 'Failed to copy');
				$('#copied-tooltip-{{report.id}}').removeClass('tooltip-accent').addClass('tooltip-error');
			})
	});
	$(`#copy-report-md-{{report.id}}`).on('mouseleave',function() {
		$('#copied-tooltip-{{report.id}}').attr('data-tip', 'Click to copy report in MD.');
		$('#copied-tooltip-{{report.id}}').removeClass('tooltip-error');
		$('#copied-tooltip-{{report.id}}').removeClass('tooltip-success');
		$('#copied-tooltip-{{report.id}}').addClass('tooltip-accent');
	})
</script>

templates/reports/index.html
{% extends "base.html" %}
{% block mainblock %}
	<main class="container w-9/10 max-w-3xl mx-auto sm:px-1 md:px-10 py-4">
		<div class="drawer">
			<input id="report-form" type="checkbox" class="drawer-toggle" />
			<div class="drawer-content">
				<div class="flex flex-row justify-between">
					<p class="font-mono text-3xl font-extrabold">日報</p>
					<label for="report-form" class="btn btn-primary drawer-button">日報を書く</label>
				</div>
				{% if report_list_by_week %}
					<div class="space-y-8">
						{% for reports_by_week in report_list_by_week %}
							{% with reports_by_week|first as head_report %}
								<div class="divider divider-accent divider-start">{{head_report.on_date|date:"Y年 第W週"}}</div>
							{% endwith %}
							<div class="space-y-4">
								{% for report in reports_by_week %}
									{% include "reports/_components/report_card.html" with report=report %}
								{% endfor %}
							</div>
						{% endfor %}
					</div>
				{% else %}
					<p>No reports are available.</p>
				{% endif %}
			</div>
			{% include "reports/_components/report_form.html" with form=form %}
		</div>
	</main>
{% endblock %}